package assignment_2;

public class Bonus {

public static Song testSong(){

SoundSet[] sounds = {
        new SoundSet(911, 65, 69, 72, 77),
        new SoundSet(49),
        new SoundSet(911, 64, 69, 72, 76),
        new SoundSet(49),
        new SoundSet(683, 67, 69, 72, 79),
        new SoundSet(37),
        new SoundSet(1139, 65, 69, 72, 77),

};
return new Song("test", sounds);
}

public static Song testSong2(){



    SoundSet[] sounds = {new SoundSet(80, 76),
            new SoundSet(40),
            new SoundSet(80, 76),
            new SoundSet(160),
            new SoundSet(80, 76),
            new SoundSet(160),
            new SoundSet(80, 72),
            new SoundSet(40),
            new SoundSet(80, 76),
            new SoundSet(160),
            new SoundSet(80, 79),
            new SoundSet(880),
            new SoundSet(80, 72),
            new SoundSet(280),
            new SoundSet(80, 67),
            new SoundSet(280),
            new SoundSet(80, 64),
            new SoundSet(280),
            new SoundSet(80, 69),
            new SoundSet(160),
            new SoundSet(80, 71),
            new SoundSet(160),
            new SoundSet(80, 70),
            new SoundSet(40),
            new SoundSet(80, 69),
            new SoundSet(160),
            new SoundSet(80, 67),
            new SoundSet(80),
            new SoundSet(80, 76),
            new SoundSet(80),
            new SoundSet(80, 79),
            new SoundSet(80),
            new SoundSet(80, 81),
            new SoundSet(160),
            new SoundSet(80, 77),
            new SoundSet(40),
            new SoundSet(80, 79),
            new SoundSet(160),
            new SoundSet(80, 76),
            new SoundSet(160),
            new SoundSet(80, 72),
            new SoundSet(40),
            new SoundSet(80, 74),
            new SoundSet(40),
            new SoundSet(80, 71),
            new SoundSet(280),
            new SoundSet(80, 72),
            new SoundSet(280),
            new SoundSet(80, 67),
            new SoundSet(280),
            new SoundSet(80, 64),
            new SoundSet(280),
            new SoundSet(80, 69),
            new SoundSet(160),
            new SoundSet(80, 71),
            new SoundSet(160),
            new SoundSet(80, 70),
            new SoundSet(40),
            new SoundSet(80, 69),
            new SoundSet(160),
            new SoundSet(80, 67),
            new SoundSet(80),
            new SoundSet(80, 76),
            new SoundSet(80),
            new SoundSet(80, 79),
            new SoundSet(80),
            new SoundSet(80, 81),
            new SoundSet(160),
            new SoundSet(80, 77),
            new SoundSet(40),
            new SoundSet(80, 79),
            new SoundSet(160),
            new SoundSet(80, 76),
            new SoundSet(160),
            new SoundSet(80, 72),
            new SoundSet(40),
            new SoundSet(80, 74),
            new SoundSet(40),
            new SoundSet(80, 71),
            new SoundSet(520),
            new SoundSet(80, 79),
            new SoundSet(40),
            new SoundSet(80, 78),
            new SoundSet(40),
            new SoundSet(80, 77),
            new SoundSet(40),
            new SoundSet(80, 75),
            new SoundSet(160),
            new SoundSet(80, 76),
            new SoundSet(160),
            new SoundSet(80, 68),
            new SoundSet(40),
            new SoundSet(80, 69),
            new SoundSet(40),
            new SoundSet(80, 72),
            new SoundSet(160),
            new SoundSet(80, 69),
            new SoundSet(40),
            new SoundSet(80, 72),
            new SoundSet(40),
            new SoundSet(80, 74),
            new SoundSet(280),
            new SoundSet(80, 79),
            new SoundSet(40),
            new SoundSet(80, 78),
            new SoundSet(40),
            new SoundSet(80, 77),
            new SoundSet(40),
            new SoundSet(80, 75),
            new SoundSet(160),
            new SoundSet(80, 76),
            new SoundSet(160),
            new SoundSet(80, 84),
            new SoundSet(160),
            new SoundSet(80, 84),
            new SoundSet(40),
            new SoundSet(80, 84),
            new SoundSet(640),
            new SoundSet(80, 79),
            new SoundSet(40),
            new SoundSet(80, 78),
            new SoundSet(40),
            new SoundSet(80, 77),
            new SoundSet(40),
            new SoundSet(80, 75),
            new SoundSet(160),
            new SoundSet(80, 76),
            new SoundSet(160),
            new SoundSet(80, 68),
            new SoundSet(40),
            new SoundSet(80, 69),
            new SoundSet(40),
            new SoundSet(80, 72),
            new SoundSet(160),
            new SoundSet(80, 69),
            new SoundSet(40),
            new SoundSet(80, 72),
            new SoundSet(40),
            new SoundSet(80, 74),
            new SoundSet(280),
            new SoundSet(80, 75),
            new SoundSet(280),
            new SoundSet(80, 74),
            new SoundSet(280),
            new SoundSet(80, 72),
            new SoundSet(1120),
            new SoundSet(80, 79),
            new SoundSet(40),
            new SoundSet(80, 78),
            new SoundSet(40),
            new SoundSet(80, 77),
            new SoundSet(40),
            new SoundSet(80, 75),
            new SoundSet(160),
            new SoundSet(80, 76),
            new SoundSet(160),
            new SoundSet(80, 68),
            new SoundSet(40),
            new SoundSet(80, 69),
            new SoundSet(40),
            new SoundSet(80, 72),
            new SoundSet(160),
            new SoundSet(80, 69),
            new SoundSet(40),
            new SoundSet(80, 72),
            new SoundSet(40),
            new SoundSet(80, 74),
            new SoundSet(280),
            new SoundSet(80, 79),
            new SoundSet(40),
            new SoundSet(80, 78),
            new SoundSet(40),
            new SoundSet(80, 77),
            new SoundSet(40),
            new SoundSet(80, 75),
            new SoundSet(160),
            new SoundSet(80, 76),
            new SoundSet(160),
            new SoundSet(80, 84),
            new SoundSet(160),
            new SoundSet(80, 84),
            new SoundSet(40),
            new SoundSet(80, 84),
            new SoundSet(640),
            new SoundSet(80, 79),
            new SoundSet(40),
            new SoundSet(80, 78),
            new SoundSet(40),
            new SoundSet(80, 77),
            new SoundSet(40),
            new SoundSet(80, 75),
            new SoundSet(160),
            new SoundSet(80, 76),
            new SoundSet(160),
            new SoundSet(80, 68),
            new SoundSet(40),
            new SoundSet(80, 69),
            new SoundSet(40),
            new SoundSet(80, 72),
            new SoundSet(160),
            new SoundSet(80, 69),
            new SoundSet(40),
            new SoundSet(80, 72),
            new SoundSet(40),
            new SoundSet(80, 74),
            new SoundSet(280),
            new SoundSet(80, 75),
            new SoundSet(280),
            new SoundSet(80, 74),
            new SoundSet(280),
            new SoundSet(80, 72),
            new SoundSet(880),
            new SoundSet(80, 72),
            new SoundSet(40),
            new SoundSet(80, 72),
            new SoundSet(160),
            new SoundSet(80, 72),
            new SoundSet(160),
            new SoundSet(80, 72),
            new SoundSet(40),
            new SoundSet(80, 74),
            new SoundSet(160),
            new SoundSet(80, 76),
            new SoundSet(40),
            new SoundSet(80, 72),
            new SoundSet(160),
            new SoundSet(80, 69),
            new SoundSet(40),
            new SoundSet(80, 67),
            new SoundSet(400),
            new SoundSet(80, 72),
            new SoundSet(40),
            new SoundSet(80, 72),
            new SoundSet(160),
            new SoundSet(80, 72),
            new SoundSet(160),
            new SoundSet(80, 72),
            new SoundSet(40),
            new SoundSet(80, 74),
            new SoundSet(40),
            new SoundSet(80, 76),
            new SoundSet(1000),
            new SoundSet(80, 72),
            new SoundSet(40),
            new SoundSet(80, 72),
            new SoundSet(160),
            new SoundSet(80, 72),
            new SoundSet(160),
            new SoundSet(80, 72),
            new SoundSet(40),
            new SoundSet(80, 74),
            new SoundSet(160),
            new SoundSet(80, 76),
            new SoundSet(40),
            new SoundSet(80, 72),
            new SoundSet(160),
            new SoundSet(80, 69),
            new SoundSet(40),
            new SoundSet(80, 67),
            new SoundSet(400),
            new SoundSet(80, 76),
            new SoundSet(40),
            new SoundSet(80, 76),
            new SoundSet(160),
            new SoundSet(80, 76),
            new SoundSet(160),
            new SoundSet(80, 72),
            new SoundSet(40),
            new SoundSet(80, 76),
            new SoundSet(160),
            new SoundSet(80, 79),
            new SoundSet(880),
            new SoundSet(80, 72),
            new SoundSet(280),
            new SoundSet(80, 67),
            new SoundSet(280),
            new SoundSet(80, 64),
            new SoundSet(280),
            new SoundSet(80, 69),
            new SoundSet(160),
            new SoundSet(80, 71),
            new SoundSet(160),
            new SoundSet(80, 70),
            new SoundSet(40),
            new SoundSet(80, 69),
            new SoundSet(160),
            new SoundSet(80, 67),
            new SoundSet(80),
            new SoundSet(80, 76),
            new SoundSet(80),
            new SoundSet(80, 79),
            new SoundSet(80),
            new SoundSet(80, 81),
            new SoundSet(160),
            new SoundSet(80, 77),
            new SoundSet(40),
            new SoundSet(80, 79),
            new SoundSet(160),
            new SoundSet(80, 76),
            new SoundSet(160),
            new SoundSet(80, 72),
            new SoundSet(40),
            new SoundSet(80, 74),
            new SoundSet(40),
            new SoundSet(80, 71),
            new SoundSet(280),
            new SoundSet(80, 72),
            new SoundSet(280),
            new SoundSet(80, 67),
            new SoundSet(280),
            new SoundSet(80, 64),
            new SoundSet(280),
            new SoundSet(80, 69),
            new SoundSet(160),
            new SoundSet(80, 71),
            new SoundSet(160),
            new SoundSet(80, 70),
            new SoundSet(40),
            new SoundSet(80, 69),
            new SoundSet(160),
            new SoundSet(80, 67),
            new SoundSet(80),
            new SoundSet(80, 76),
            new SoundSet(80),
            new SoundSet(80, 79),
            new SoundSet(80),
            new SoundSet(80, 81),
            new SoundSet(160),
            new SoundSet(80, 77),
            new SoundSet(40),
            new SoundSet(80, 79),
            new SoundSet(160),
            new SoundSet(80, 76),
            new SoundSet(160),
            new SoundSet(80, 72),
            new SoundSet(40),
            new SoundSet(80, 74),
            new SoundSet(40),
            new SoundSet(80, 71),
            new SoundSet(280),
            new SoundSet(80, 76),
            new SoundSet(40),
            new SoundSet(80, 72),
            new SoundSet(160),
            new SoundSet(80, 67),
            new SoundSet(280),
            new SoundSet(80, 68),
            new SoundSet(160),
            new SoundSet(80, 69),
            new SoundSet(40),
            new SoundSet(80, 77),
            new SoundSet(160),
            new SoundSet(80, 77),
            new SoundSet(40),
            new SoundSet(80, 69),
            new SoundSet(400),
            new SoundSet(80, 71),
            new SoundSet(80),
            new SoundSet(80, 81),
            new SoundSet(80),
            new SoundSet(80, 81),
            new SoundSet(80),
            new SoundSet(80, 81),
            new SoundSet(80),
            new SoundSet(80, 79),
            new SoundSet(80),
            new SoundSet(80, 77),
            new SoundSet(80),
            new SoundSet(80, 76),
            new SoundSet(40),
            new SoundSet(80, 72),
            new SoundSet(160),
            new SoundSet(80, 69),
            new SoundSet(40),
            new SoundSet(80, 67),
            new SoundSet(400),
            new SoundSet(80, 76),
            new SoundSet(40),
            new SoundSet(80, 72),
            new SoundSet(160),
            new SoundSet(80, 67),
            new SoundSet(280),
            new SoundSet(80, 68),
            new SoundSet(160),
            new SoundSet(80, 69),
            new SoundSet(40),
            new SoundSet(80, 77),
            new SoundSet(160),
            new SoundSet(80, 77),
            new SoundSet(40),
            new SoundSet(80, 69),
            new SoundSet(400),
            new SoundSet(80, 71),
            new SoundSet(40),
            new SoundSet(80, 77),
            new SoundSet(160),
            new SoundSet(80, 77),
            new SoundSet(40),
            new SoundSet(80, 77),
            new SoundSet(80),
            new SoundSet(80, 76),
            new SoundSet(80),
            new SoundSet(80, 74),
            new SoundSet(80),
            new SoundSet(80, 72),
            new SoundSet(880),
            new SoundSet(80, 76),
            new SoundSet(40),
            new SoundSet(80, 72),
            new SoundSet(160),
            new SoundSet(80, 67),
            new SoundSet(280),
            new SoundSet(80, 68),
            new SoundSet(160),
            new SoundSet(80, 69),
            new SoundSet(40),
            new SoundSet(80, 77),
            new SoundSet(160),
            new SoundSet(80, 77),
            new SoundSet(40),
            new SoundSet(80, 69),
            new SoundSet(400),
            new SoundSet(80, 71),
            new SoundSet(80),
            new SoundSet(80, 81),
            new SoundSet(80),
            new SoundSet(80, 81),
            new SoundSet(80),
            new SoundSet(80, 81),
            new SoundSet(80),
            new SoundSet(80, 79),
            new SoundSet(80),
            new SoundSet(80, 77),
            new SoundSet(80),
            new SoundSet(80, 76),
            new SoundSet(40),
            new SoundSet(80, 72),
            new SoundSet(160),
            new SoundSet(80, 69),
            new SoundSet(40),
            new SoundSet(80, 67),
            new SoundSet(400),
            new SoundSet(80, 76),
            new SoundSet(40),
            new SoundSet(80, 72),
            new SoundSet(160),
            new SoundSet(80, 67),
            new SoundSet(280),
            new SoundSet(80, 68),
            new SoundSet(160),
            new SoundSet(80, 69),
            new SoundSet(40),
            new SoundSet(80, 77),
            new SoundSet(160),
            new SoundSet(80, 77),
            new SoundSet(40),
            new SoundSet(80, 69),
            new SoundSet(400),
            new SoundSet(80, 71),
            new SoundSet(40),
            new SoundSet(80, 77),
            new SoundSet(160),
            new SoundSet(80, 77),
            new SoundSet(40),
            new SoundSet(80, 77),
            new SoundSet(80),
            new SoundSet(80, 76),
            new SoundSet(80),
            new SoundSet(80, 74),
            new SoundSet(80),
            new SoundSet(80, 72),
            new SoundSet(880),
            new SoundSet(80, 72),
            new SoundSet(40),
            new SoundSet(80, 72),
            new SoundSet(160),
            new SoundSet(80, 72),
            new SoundSet(160),
            new SoundSet(80, 72),
            new SoundSet(40),
            new SoundSet(80, 74),
            new SoundSet(160),
            new SoundSet(80, 76),
            new SoundSet(40),
            new SoundSet(80, 72),
            new SoundSet(160),
            new SoundSet(80, 69),
            new SoundSet(40),
            new SoundSet(80, 67),
            new SoundSet(400),
            new SoundSet(80, 72),
            new SoundSet(40),
            new SoundSet(80, 72),
            new SoundSet(160),
            new SoundSet(80, 72),
            new SoundSet(160),
            new SoundSet(80, 72),
            new SoundSet(40),
            new SoundSet(80, 74),
            new SoundSet(40),
            new SoundSet(80, 76),
            new SoundSet(1000),
            new SoundSet(80, 72),
            new SoundSet(40),
            new SoundSet(80, 72),
            new SoundSet(160),
            new SoundSet(80, 72),
            new SoundSet(160),
            new SoundSet(80, 72),
            new SoundSet(40),
            new SoundSet(80, 74),
            new SoundSet(160),
            new SoundSet(80, 76),
            new SoundSet(40),
            new SoundSet(80, 72),
            new SoundSet(160),
            new SoundSet(80, 69),
            new SoundSet(40),
            new SoundSet(80, 67),
            new SoundSet(400),
            new SoundSet(80, 76),
            new SoundSet(40),
            new SoundSet(80, 76),
            new SoundSet(160),
            new SoundSet(80, 76),
            new SoundSet(160),
            new SoundSet(80, 72),
            new SoundSet(40),
            new SoundSet(80, 76),
            new SoundSet(160),
            new SoundSet(80, 79),
            new SoundSet(880),
            new SoundSet(80, 76),
            new SoundSet(40),
            new SoundSet(80, 72),
            new SoundSet(160),
            new SoundSet(80, 67),
            new SoundSet(280),
            new SoundSet(80, 68),
            new SoundSet(160),
            new SoundSet(80, 69),
            new SoundSet(40),
            new SoundSet(80, 77),
            new SoundSet(160),
            new SoundSet(80, 77),
            new SoundSet(40),
            new SoundSet(80, 69),
            new SoundSet(400),
            new SoundSet(80, 71),
            new SoundSet(80),
            new SoundSet(80, 81),
            new SoundSet(80),
            new SoundSet(80, 81),
            new SoundSet(80),
            new SoundSet(80, 81),
            new SoundSet(80),
            new SoundSet(80, 79),
            new SoundSet(80),
            new SoundSet(80, 77),
            new SoundSet(80),
            new SoundSet(80, 76),
            new SoundSet(40),
            new SoundSet(80, 72),
            new SoundSet(160),
            new SoundSet(80, 69),
            new SoundSet(40),
            new SoundSet(80, 67),
            new SoundSet(400),
            new SoundSet(80, 76),
            new SoundSet(40),
            new SoundSet(80, 72),
            new SoundSet(160),
            new SoundSet(80, 67),
            new SoundSet(280),
            new SoundSet(80, 68),
            new SoundSet(160),
            new SoundSet(80, 69),
            new SoundSet(40),
            new SoundSet(80, 77),
            new SoundSet(160),
            new SoundSet(80, 77),
            new SoundSet(40),
            new SoundSet(80, 69),
            new SoundSet(400),
            new SoundSet(80, 71),
            new SoundSet(40),
            new SoundSet(80, 77),
            new SoundSet(160),
            new SoundSet(80, 77),
            new SoundSet(40),
            new SoundSet(80, 77),
            new SoundSet(80),
            new SoundSet(80, 76),
            new SoundSet(80),
            new SoundSet(80, 74),
            new SoundSet(80),
            new SoundSet(80, 72),
            new SoundSet(80),
            new SoundSet(80, 72),
            new SoundSet(80),

    };


    return new Song("test", sounds);
}


    public static void main(String[] args) {
//        Piano piano = new Piano();
//        piano.playSong(testSong2());

        Xylophone xylophone = new Xylophone();
        xylophone.playSong(testSong2());

//        Trumpet trumpet = new Trumpet();
//        trumpet.playSong(testSong2());
    }
}
